# Generated by Django 2.2.6 on 2019-11-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_lelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availibility',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
